module.exports = {
    en: {
        'class': 'Class',
        method: 'Method',
        property: 'Property',
        namespace: 'Namespace',
        arguments: 'Arguments',
        properties: 'Properties',
        examples: 'Examples',
        name: 'Name',
        type: 'Type',
        'default': 'Default',
        details: 'Details',
        returns: 'Returns',
        fires: 'Fires',
        comments: 'ASK A QUESTION',
        see: 'Links',
        methods: 'Methods',
        properties: 'Properties',
        static_methods: 'Static Methods',
        static_properties: 'Static Props'
    },
    ru: {
        'class': 'Класс',
        method: 'Метод',
        property: 'Свойство',
        namespace: 'Пространство имен',
        arguments: 'Аргументы',
        properties: 'Свойства',
        examples: 'Примеры',
        name: 'Имя',
        type: 'Тип',
        'default': 'По&nbsp;умолчанию',
        details: 'Описание',
        returns: 'Возвращает',
        fires: 'Генерирует события',
        comments: 'Задать вопрос',
        see: 'Ссылки',
        methods: 'Методы',
        properties: 'Свойства',
        static_methods: 'Статичные методы',
        static_properties: 'Статичные свойства'
    }
};
