module.exports = {
    en: {
        class: 'Class',
        method: 'Method',
        property: 'Property',
        namespace: 'Namespace',
        arguments: 'Arguments',
        properties: 'Properties',
        examples: 'Examples',
        name: 'Name',
        type: 'Type',
        default: 'Default',
        details: 'Details',
        returns: 'Returns',
        fires: 'Fires',
        comments: 'Ask a question',
        see: 'Links',
        methods: 'Methods',
        properties: 'Properties',
        static_methods: 'Static Methods',
        static_properties: 'Static Props',
        synonym: 'Synonym',
        module: 'CommonJS module',
        patchLinkText: 'Found an ussue in the article? Send a patch there.'
    },
    ua: {
        class: 'Клас',
        method: 'Метод',
        property: 'Властивість',
        namespace: 'Простір імен',
        arguments: 'Аргументи',
        properties: 'Властивості',
        examples: 'Приклади',
        name: 'Iм\'я',
        type: 'Тип',
        default: 'За&nbsp;замовчуванням',
        details: 'Опис',
        returns: 'Повертає',
        fires: 'Генерує події',
        comments: 'Задати питання',
        see: 'Посилання',
        methods: 'Методи',
        static_methods: 'Статичні методи',
        static_properties: 'Статичні властивості',
        synonym: 'Синонім',
        module: 'Шлях до модуля CommonJS',
        patchLinkText: 'Знайшли помилку в статті? Надішліть патч з виправленням.'
    },
    ru: {
        class: 'Класс',
        method: 'Метод',
        property: 'Свойство',
        namespace: 'Пространство имен',
        arguments: 'Аргументы',
        properties: 'Свойства',
        examples: 'Примеры',
        name: 'Имя',
        type: 'Тип',
        default: 'По&nbsp;умолчанию',
        details: 'Описание',
        returns: 'Возвращает',
        fires: 'Генерирует события',
        comments: 'Задать вопрос',
        see: 'Ссылки',
        methods: 'Методы',
        static_methods: 'Статичные методы',
        static_properties: 'Статичные свойства',
        synonym: 'Синоним',
        module: 'Путь к модулю CommonJS',
        patchLinkText: 'Нашли ошибку в статье? Пришлите патч с исправлением.'
    }
};
